#!/usr/bin/with-contenv sh



run_wp(){
  
  eval "su - nginx -s /bin/ash -c 'cd /var/www/wordpress/ && "$@"'" 
  return $? 
}


install(){

    if [ -z "$(ls -A "/var/www/wordpress/index.php")" ]; 
    then 
      if [ ! -d /var/www/wordpress ]; 
      then 
        mkdir /var/www/wordpress 
      fi 

      chown nginx:nginx  /var/www/wordpress -R

      cd /var/www/wordpress 
      run_wp wp core download
      run_wp wp core config --dbprefix='wpi_' --dbhost=${DATABASE_HOST}  --dbname=${DATABASE_NAME} --dbuser=${DATABASE_USERNAME} --dbpass=${DATABASE_PASSWORD}
     

    fi

    chown nginx:nginx /var/www/wordpress -R
    return 0

}



config(){

    if [ $( run_wp $(echo 'wp core is-installed') ) ]; 
    then
        echo "Already Installed"
    else

        while ! $( nc -vz ${DATABASE_HOST} ${DATABASE_PORT} ) ;
        do
            sleep 1
        done

        run_wp $( echo 'wp core install --url="'$TRUSTED_DOMAIN'" --title="'$SITENAME'" --admin_user="'$ADMIN_USERNAME'" --admin_password="'$ADMIN_PASSWORD'" --admin_email="'$ADMIN_EMAIL'"' )

    fi 

    return 0
    
}



fix_https(){
    grep -v "//HTTPSFIX" /var/www/wordpress/wp-config.php > temp && mv temp /var/www/wordpress/wp-config.php
    grep -v "wp-settings.php" /var/www/wordpress/wp-config.php > temp && mv temp /var/www/wordpress/wp-config.php

    echo 'if( isset($_SERVER["HTTP_X_FORWARDED_PROTO"]) && ($_SERVER["HTTP_X_FORWARDED_PROTO"] == "https")){ //HTTPSFIX' >> /var/www/wordpress/wp-config.php
    echo '        $_SERVER["HTTPS"] = "on"; //HTTPSFIX'  >> /var/www/wordpress/wp-config.php
    echo '        $_SERVER["SERVER_PORT"] = 443; //HTTPSFIX'  >> /var/www/wordpress/wp-config.php
    echo '} //HTTPSFIX'  >> /var/www/wordpress/wp-config.php
    echo 'require_once ABSPATH . "wp-settings.php";'  >> /var/www/wordpress/wp-config.php
    return 0
}


fail(){

  echo "1" > /tmp/wordpress

}

success(){

  echo "0" > /tmp/wordpress

}




install  &&  config && fix_https && success || fail